title: Jennifer Johansson # your name (or website title) here
logo: "/images/Jen_thumbnail.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science Student and <br>
  experienced Customer Success Manager 
  <br><br>
  Exploring opportunities to merge Data Science with People and Business Management
  <br><br>
  <a href="https://www.linkedin.com/in/jennifer-johansson-88b99432/">View My LinkedIn Profile</a> 
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
