title: Jennifer Johansson # your name (or website title) here
logo: "/images/jen_thumbnail.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science Student<br>
  and <br>
  experienced Customer Success Manager 
  <br><br>
  exploring opportunities to merge data science with people and business management
  <br><br>
  <a href="https://www.linkedin.com/in/jennifer-johansson-88b99432/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
